/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraduzirRouteImport } from './routes/traduzir'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as ConversaRouteImport } from './routes/conversa'
import { Route as IndexRouteImport } from './routes/index'

const TraduzirRoute = TraduzirRouteImport.update({
  id: '/traduzir',
  path: '/traduzir',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaRoute = ConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/hospital': typeof HospitalRoute
  '/traduzir': typeof TraduzirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/hospital': typeof HospitalRoute
  '/traduzir': typeof TraduzirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/hospital': typeof HospitalRoute
  '/traduzir': typeof TraduzirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversa' | '/hospital' | '/traduzir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversa' | '/hospital' | '/traduzir'
  id: '__root__' | '/' | '/conversa' | '/hospital' | '/traduzir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversaRoute: typeof ConversaRoute
  HospitalRoute: typeof HospitalRoute
  TraduzirRoute: typeof TraduzirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traduzir': {
      id: '/traduzir'
      path: '/traduzir'
      fullPath: '/traduzir'
      preLoaderRoute: typeof TraduzirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa': {
      id: '/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof ConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversaRoute: ConversaRoute,
  HospitalRoute: HospitalRoute,
  TraduzirRoute: TraduzirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
