/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ConversaRouteImport } from './routes/conversa'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as LiaRouteImport } from './routes/lia'
import { Route as TraduzirRouteImport } from './routes/traduzir'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as BibliotecaAdminRouteImport } from './routes/biblioteca.admin'
import { Route as EducacaoSlugRouteImport } from './routes/educacao.$slug'
import { Route as ApiPublicAulasRouteImport } from './routes/api/public/aulas'
import { Route as ApiPublicHospitalPhrasesRouteImport } from './routes/api/public/hospital-phrases'
import { Route as ApiPublicSignsRouteImport } from './routes/api/public/signs'
import { Route as ApiPublicTranslateRouteImport } from './routes/api/public/translate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaRoute = ConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LiaRoute = LiaRouteImport.update({
  id: '/lia',
  path: '/lia',
  getParentRoute: () => rootRouteImport,
} as any)
const TraduzirRoute = TraduzirRouteImport.update({
  id: '/traduzir',
  path: '/traduzir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BibliotecaAdminRoute = BibliotecaAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BibliotecaRoute,
} as any)
const EducacaoSlugRoute = EducacaoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EducacaoRoute,
} as any)
const ApiPublicAulasRoute = ApiPublicAulasRouteImport.update({
  id: '/api/public/aulas',
  path: '/api/public/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHospitalPhrasesRoute =
  ApiPublicHospitalPhrasesRouteImport.update({
    id: '/api/public/hospital-phrases',
    path: '/api/public/hospital-phrases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSignsRoute = ApiPublicSignsRouteImport.update({
  id: '/api/public/signs',
  path: '/api/public/signs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranslateRoute = ApiPublicTranslateRouteImport.update({
  id: '/api/public/translate',
  path: '/api/public/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conversa': typeof ConversaRoute
  '/educacao': typeof EducacaoRouteWithChildren
  '/hospital': typeof HospitalRoute
  '/lia': typeof LiaRoute
  '/traduzir': typeof TraduzirRoute
  '/conta': typeof AuthenticatedContaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/educacao/$slug': typeof EducacaoSlugRoute
  '/api/public/aulas': typeof ApiPublicAulasRoute
  '/api/public/hospital-phrases': typeof ApiPublicHospitalPhrasesRoute
  '/api/public/signs': typeof ApiPublicSignsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conversa': typeof ConversaRoute
  '/educacao': typeof EducacaoRouteWithChildren
  '/hospital': typeof HospitalRoute
  '/lia': typeof LiaRoute
  '/traduzir': typeof TraduzirRoute
  '/conta': typeof AuthenticatedContaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/educacao/$slug': typeof EducacaoSlugRoute
  '/api/public/aulas': typeof ApiPublicAulasRoute
  '/api/public/hospital-phrases': typeof ApiPublicHospitalPhrasesRoute
  '/api/public/signs': typeof ApiPublicSignsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conversa': typeof ConversaRoute
  '/educacao': typeof EducacaoRouteWithChildren
  '/hospital': typeof HospitalRoute
  '/lia': typeof LiaRoute
  '/traduzir': typeof TraduzirRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/educacao/$slug': typeof EducacaoSlugRoute
  '/api/public/aulas': typeof ApiPublicAulasRoute
  '/api/public/hospital-phrases': typeof ApiPublicHospitalPhrasesRoute
  '/api/public/signs': typeof ApiPublicSignsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/auth'
    | '/biblioteca'
    | '/conversa'
    | '/educacao'
    | '/hospital'
    | '/lia'
    | '/traduzir'
    | '/conta'
    | '/usuarios'
    | '/biblioteca/admin'
    | '/educacao/$slug'
    | '/api/public/aulas'
    | '/api/public/hospital-phrases'
    | '/api/public/signs'
    | '/api/public/translate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprender'
    | '/auth'
    | '/biblioteca'
    | '/conversa'
    | '/educacao'
    | '/hospital'
    | '/lia'
    | '/traduzir'
    | '/conta'
    | '/usuarios'
    | '/biblioteca/admin'
    | '/educacao/$slug'
    | '/api/public/aulas'
    | '/api/public/hospital-phrases'
    | '/api/public/signs'
    | '/api/public/translate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprender'
    | '/auth'
    | '/biblioteca'
    | '/conversa'
    | '/educacao'
    | '/hospital'
    | '/lia'
    | '/traduzir'
    | '/_authenticated/conta'
    | '/_authenticated/usuarios'
    | '/biblioteca/admin'
    | '/educacao/$slug'
    | '/api/public/aulas'
    | '/api/public/hospital-phrases'
    | '/api/public/signs'
    | '/api/public/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprenderRoute: typeof AprenderRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ConversaRoute: typeof ConversaRoute
  EducacaoRoute: typeof EducacaoRouteWithChildren
  HospitalRoute: typeof HospitalRoute
  LiaRoute: typeof LiaRoute
  TraduzirRoute: typeof TraduzirRoute
  ApiPublicAulasRoute: typeof ApiPublicAulasRoute
  ApiPublicHospitalPhrasesRoute: typeof ApiPublicHospitalPhrasesRoute
  ApiPublicSignsRoute: typeof ApiPublicSignsRoute
  ApiPublicTranslateRoute: typeof ApiPublicTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa': {
      id: '/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof ConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lia': {
      id: '/lia'
      path: '/lia'
      fullPath: '/lia'
      preLoaderRoute: typeof LiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traduzir': {
      id: '/traduzir'
      path: '/traduzir'
      fullPath: '/traduzir'
      preLoaderRoute: typeof TraduzirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/biblioteca/admin': {
      id: '/biblioteca/admin'
      path: '/admin'
      fullPath: '/biblioteca/admin'
      preLoaderRoute: typeof BibliotecaAdminRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/educacao/$slug': {
      id: '/educacao/$slug'
      path: '/$slug'
      fullPath: '/educacao/$slug'
      preLoaderRoute: typeof EducacaoSlugRouteImport
      parentRoute: typeof EducacaoRoute
    }
    '/api/public/aulas': {
      id: '/api/public/aulas'
      path: '/api/public/aulas'
      fullPath: '/api/public/aulas'
      preLoaderRoute: typeof ApiPublicAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hospital-phrases': {
      id: '/api/public/hospital-phrases'
      path: '/api/public/hospital-phrases'
      fullPath: '/api/public/hospital-phrases'
      preLoaderRoute: typeof ApiPublicHospitalPhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signs': {
      id: '/api/public/signs'
      path: '/api/public/signs'
      fullPath: '/api/public/signs'
      preLoaderRoute: typeof ApiPublicSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/translate': {
      id: '/api/public/translate'
      path: '/api/public/translate'
      fullPath: '/api/public/translate'
      preLoaderRoute: typeof ApiPublicTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BibliotecaRouteChildren {
  BibliotecaAdminRoute: typeof BibliotecaAdminRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaAdminRoute: BibliotecaAdminRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface EducacaoRouteChildren {
  EducacaoSlugRoute: typeof EducacaoSlugRoute
}

const EducacaoRouteChildren: EducacaoRouteChildren = {
  EducacaoSlugRoute: EducacaoSlugRoute,
}

const EducacaoRouteWithChildren = EducacaoRoute._addFileChildren(
  EducacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprenderRoute: AprenderRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ConversaRoute: ConversaRoute,
  EducacaoRoute: EducacaoRouteWithChildren,
  HospitalRoute: HospitalRoute,
  LiaRoute: LiaRoute,
  TraduzirRoute: TraduzirRoute,
  ApiPublicAulasRoute: ApiPublicAulasRoute,
  ApiPublicHospitalPhrasesRoute: ApiPublicHospitalPhrasesRoute,
  ApiPublicSignsRoute: ApiPublicSignsRoute,
  ApiPublicTranslateRoute: ApiPublicTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
